### PR TITLE
…Added pcb files for downwards plugs

### PR DESCRIPTION
**Pull request by Skylark13**
Added pcb files for downwards plugs, useful on Crosspoint switches with inputs and outputs in 2 lines very close to each other.

Example: Extron Crosspoint 1616 : https://www.extron.com/product/crosspoint1616

This way, the adapters for the inputs are soldered to the top of the PCB so the RCA jacks go up from the PCB, and the adapters for the outputs are soldered to the bottom of the PCB so the RCA jacks go down from the PCB. But I did not want to restrict this to only that use case, so I made "downwards" versions of both the input and output PCB designs.

And yes, I know the downwards adapters will probably not fit if the switch is resting on a flat surface. I will have to prop it up by a few cm. But it's better than nothing. :)

image

### CODE REVIEW

**Comment by tcdev42** [comment]
Hi. Could you please let me know the part number for the phoenix connectors?

I ordered Molex 0395005005 from Digikey and they're too wide to fit side-by-side (18.30mm). Digikey have an alternate part, Tyco Buchanan 284506-5 (17.5mm) but I'm not sure it's sufficient - and they're almost twice the price!

TIA!
Mark

**Comment by Skylark13** [comment]
Hi Mark,

I ordered them from AliExpress, and the ones I got were 18.0mm wide, and they're tight but they fit side by side. See this tweet (in French...)
https://twitter.com/js_guay/status/1184639960470753280

The item I ordered from AliExpress is this one, but I'm not 100% sure you can guarantee you will always get the same from all sellers or even the same seller, I think I just got lucky...
https://www.aliexpress.com/item/32807773346.html
(5 pin * 10 connectors, and I orderd 2, because I needed 12 input and 8 output plugs to start with)

**Comment by tcdev42** [comment]
Thanks, at that price I can give it a go without losing much...

**Comment by tcdev42** [comment]
I think the trick is to buy the 10-pin connector and screw two boards into it.

**Comment by Skylark13** [comment]
That would probably work better yes, since as you can see in the photo above the female connectors on the Crosspoint are 10-pin, with two inputs/outputs on each.

Still, I like the flexibility to be able to remove each one independently, and as I said the ones I ordered, even though they fit tight, they fit. So it's fine for me.

**Pull request merged**
